### ISSUE TITLE
nvim-treesitter fails to load the pkl parser

### ISSUE THREAD

**Issue by marmoute** [apple/pkl-neovim#15]
I installed pkl-neovim using the recommanded config for "lazy.nvim" but it did not result in a working install. `:checkhealth nvim-treesitter` give me the following error

```
The following errors have been detected: ~
- ERROR pkl(locals): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 1024 for language pkl
  pkl(locals) is concatenated from the following files:
  | [ERROR]:"/home/marmoute/.local/share/nvim/lazy/pkl-neovim/queries/pkl/locals.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 1024 for language pkl
```

I tried the recommandation at https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position without success.

Any idea of what's going wrong ?

**Comment by bioball** [comment]
This is fixed by https://github.com/apple/pkl-neovim/pull/14

**Comment by bioball** [comment]
Given that error message, it sounds like you need to run `:TSInstall pkl`

**Comment by bioball** [comment]
Can you run `:TSUpdate`, then `:TSInstall pkl`?

As for that undefined global, seems like it's some [editor setting that you need to configure](https://www.reddit.com/r/neovim/comments/1avouc4/lua_why_warning_message_undefined_global_keywords/).

**Comment by bioball** [comment]
We extend nvim-treesitter to add pkl as a language here: https://github.com/apple/pkl-neovim/blob/main/lua/pkl-neovim/internal.lua

Maybe try adding that code directly to your init.vim and see if that helps?

Personally, I use [vim-plug](https://github.com/junegunn/vim-plug), which works just fine for me.

CC @gibfahn who also uses Lazy

**Comment by marmoute** [comment]
> @marmoute can you confirm whether your issue is resolved?

I ran TSUpdarte and TSInstall and I still get the following error.

```
The following errors have been detected:
- ERROR pkl(locals): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 1024 for language pkl
  pkl(locals) is concatenated from the following files:
  | [ERROR]:"/home/marmoute/.local/share/nvim/lazy/pkl-neovim/queries/pkl/locals.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 1024 for language pkl
```

**Comment by bioball** [comment]
Can you try the instructions provided in https://github.com/apple/pkl-neovim/pull/20?

See https://github.com/apple/pkl-neovim/pull/20/files
